### ISSUE TITLE
RHS - Marksman scopes messed up.

### ISSUE THREAD

**Issue by Tachii** [KoffeinFlummi/AGM_Compatibility#12]
Try to place marksmen unit in editor(US faction).

**Comment by jonpas** [comment]
Apparently the config inheritance is not like that for `ItemInfo` of `rhsusf_acc_LEUPOLDMK4`, because the RPT gets spamed by:
`Warning Message: No entry 'bin\config.bin/CfgWeapons/rhsusf_acc_LEUPOLDMK4/ItemInfo/OpticsModes/pso1_scope.<insert property>`

**Comment by jonpas** [comment]
It's RHS issue, running without AGM same errors. I looked into the config and it's empty, only property is `scope = 2`, so either they enabled it and it's not finished yet or forgot to put it in.
