### ISSUE TITLE
Air Drop Ammo Boxes

### ISSUE THREAD

**Issue by kripto202** [KoffeinFlummi/AGM_Compatibility#20]
When you let go of something via sling rope, the item just drops and possibly gets damaged. How about if you drop the item at a certain height, a parachute opens up.

**Comment by jonpas** [comment]
Are you sure this fits into AGM Compatibility?

**Comment by kripto202** [comment]
I wouldnt say that. I think of it as attaching a parachute to the object being dropped via slingrope

**Comment by jonpas** [comment]
Moved to https://github.com/KoffeinFlummi/AGM/issues/1979
