### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by CombustingBats** [KoffeinFlummi/AGM_Compatibility#25]
This may seem like a dumb question, but how do I use the AGM compatibility master folder to make AGM compatible with RHS escalation?  I've tried using the binarizer but I'm not sure how it works and it  crashes to desktop after giving all the file paths, with this error log:

Traceback <most recent call last>:
File "C:\Python\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
File "P:\AGM\binarizer.py", line 268, in <module>
File "P:\AGM\binarizer.py", line 251, in main
File "P:\AGM\binarizer.py", line 138, in remove_obsolete
File "P:\AGM\binarizer.py", line 87, in get_obsolete
OSError: [WinError 123] The file name, directory name or volume label syntax is incorrect: 'C:\\Users\\Ryan\\Downloads\\AGM_Compatiblity-master\\AGM_Comp_RHS_USF\\''C:\\Program Files (x86)\\Steam\\SteamApps\\common\\Arma 3\\@RHSUSF"\\addons'

Sorry if it isn't formatted well, I had to screenshot before cmd crashed and type it out.

**Comment by KoffeinFlummi** [comment]
Just use the regular addon builder right now, there's still some issues with using the binarizer for this.

**Comment by CombustingBats** [comment]
Thanks for the help, it worked like a charm.

**Comment by jonpas** [comment]
Binarizer works fine for me, just have to make the folder beforehand.
