### ISSUE TITLE
Error when launching ArmA 3 (RHS: Escalation)

### ISSUE THREAD

**Issue by CombustingBats** [KoffeinFlummi/AGM_Compatibility#27]
Whenever I launch ArmA 3, it always tells me the following:

Addon 'AGM_Comp_RHS_USF' requires addon 'rhsusf_c_a2port_air'.

I have both of these files in the same addon folder, and I'm not sure what's causing the problem.  I can play DUWS singleplayer just fine, but whenever I try to load a savegame of Pilgrimage, I get the following error:

You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.rhsusf_c_a2port_air

**Comment by esteldunedain** [comment]
This was fixed yesterday on this PR: https://github.com/KoffeinFlummi/AGM_Compatibility/pull/26

**Comment by jonpas** [comment]
Yup, that was totally my bad. :)
