### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by idkwidlol** [KoffeinFlummi/AGM_Compatibility#37]

**Comment by gpgpgpgp** [comment]
AFAIK,
1.Download everything.
2.Pack 'em up with cpbo or binarizer.exe & BI tools combination.
3.Enjoy.

**Comment by KoffeinFlummi** [comment]
As @gpgpgpgp said, at the moment there are no official PBOs available for download, so you'd have to download the archive yourself (using git or the "Download ZIP" button on the main repo page) and pack the folders you need using Addon Bilder (part of the Arma 3 Tools found in Steam).
