### ISSUE TITLE
Community Upgrade Project

### ISSUE THREAD

**Issue by bux578** [KoffeinFlummi/AGM_Compatibility#5]
**State:** Golden 9/10

------ 

- [ ] Top Down Attack for Javelin
- [ ] Scopes
- [ ] Disposable launchers?
- [x] Bullet Mass
- [x] Barrel swap
- [x] Jam Chance
- [x] Bipods
- [ ] Explosives
- [x] Backblast
- [x] some reliabilty data for MGs

------ 

~~- [ ] Improve backblast~~
~~- [ ] audibleFire values (this is something they should do themselves though)~~

------ 

http://forums.bistudio.com/showthread.php?169933-Community-Upgrade-Project

Dslyecxi on CUP Weapons:
https://www.youtube.com/watch?v=_AFebIotSOE

**Comment by Winter259** [comment]
I submitted a pull request a few minutes ago for Javelin top down attack. I've also done backblast and disposable for the rest of the launchers (where applicable) and once I get them sanity checked i'll submit two more pull requests.

**Comment by Cyruz143** [comment]
CUP pushed all of these in to the base configs bar the disposables, might want to remove the redundant ones to avoid confusion now!

**Comment by kripto202** [comment]
if i remember right the disposable rocket launcher is already in rhs

**Comment by simonamdev** [comment]
RHS and CUP are two separate packs though. If someone wants to run the RHS disposable they can just not include the CUP AGM compatibility patch.
